- name: Add the AdoptOpenJDK signing key ======================================= apt
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present

- name: Add the AdoptOpenJDK apt repository =============================================== apt
  apt_repository:
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bionic main
    filename: adoptopenjdk
    state: present

- name: Update apt ========================================== apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install AdoptOpenJDK JRE 8 ================================ apt
  apt: name=adoptopenjdk-8-hotspot-jre state=latest


