
- name: Set nodejs version ============================================= apt
  set_fact:
    nodejs_version: "10.x"

- name: Import Nodesource .deb key 
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add Nodesource repositories for Node.js
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: node_repo.changed

- name: Remove old npm version
  apt:
    name: npm
    state: absent

- name: Make sure Node.js and npm are installed
  apt:
    name: "nodejs-{{ nodejs_version|regex_replace('x', '') }}*"
    state: present
    enablerepo: nodesource

- name: Create a symlink between nodejs and node
  file: src=/usr/bin/node dest=/usr/bin/nodejs state=link

- name: Create Grunt build config
  become_user: "{{ app.name }}"
  template:
    src: "config.json.j2"
    dest: "{{ app.directory }}/config.json"

- name: Make sure npm package dependencies are installed
  become_user: "{{ app.name }}"
  command: npm install
  args:
    chdir: "{{ app.directory }}"

- name: Build Intake24 admin tool
  become_user: "{{ app.name }}"
  command: npm run build
  args:
    chdir: "{{ app.directory }}"

- name: Bind only to local interface
  become_user: "{{ app.name }}"
  lineinfile:
    dest: "{{ app.directory }}/app.js"
    regexp: "^app.listen"
    line: "app.listen({{ app.http_port }}, '{{ app.http_address }}');"

- name: Make sure i18n directory exists
  become_user: "{{ app.name }}"
  file:
    name: "{{ app.directory }}/public/i18n"
    state: directory
    owner: "{{ app.name }}"
    group: "{{ app.name }}"

- name: Build message files
  become_user: "{{ app.name }}"
  command: npm run i18n
  args:
      chdir: "{{ app.directory }}"

