
- name: Wait up to 120 seconds for host to become reachable =========================== yum
  wait_for_connection:
    timeout: 120

- name: Create deploy user =========================== yum
  user: name=deploy state=present groups=wheel shell=/bin/bash

- name: Add deploy key =========================== yum
  authorized_key: user=deploy key="{{ lookup('file', deploy_user.ssh_public_key_path) }}"

- name: Add deploy users to sudoers =========================== yum
  lineinfile: dest=/etc/sudoers line='deploy ALL=(ALL:ALL) NOPASSWD:ALL' regexp='^deploy ALL=' state=present

- name: Disable root login =========================== yum
  lineinfile: dest=/etc/ssh/sshd_config line="PermitRootLogin no" regexp="^PermitRootLogin" state=present

- name: Restart sshd =========================== yum
  service: name=sshd state=restarted

