- import_tasks: intake24-admin-deploy-from-git-yum.yml
  when: ansible_pkg_mgr == "yum" and ansible_os_family == "RedHat"

- import_tasks: intake24-admin-deploy-from-git-apt.yml
  when: ansible_pkg_mgr == "apt"

- name: Make sure .ssh directory exists for intake24-admin
  file:
    name: /home/{{ app.name }}/.ssh
    state: directory
    owner: "{{ app.name }}"
    group: "{{ app.name }}"

- name: Make sure application directory exists
  file:
    path: "{{ app.directory }}"
    state: directory
    owner: "{{ app.name }}"
    group: "{{ app.name }}"

- name: Checkout source from Git repository
  become_user: "{{ app.name }}"
  git:
    repo: "{{ git.repository_url }}"
    dest: "{{ app.directory }}"
    version: "{{ git.branch_name }}"
    force: yes
    accept_hostkey: true

